/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.4-86-g1f3baf7218-20240611"
#endif /* AVUTIL_FFVERSION_H */
