/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.6-9-gdcdfd7fb62-20241106"
#endif /* AVUTIL_FFVERSION_H */
