/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.2-8-g5746987bad-20221201"
#endif /* AVUTIL_FFVERSION_H */
