/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.2-30-gb8fe1bc38e-20250526"
#endif /* AVUTIL_FFVERSION_H */
