/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.2-6-gf749aaf108-20240911"
#endif /* AVUTIL_FFVERSION_H */
