/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.2-29-g8723e83699-20250521"
#endif /* AVUTIL_FFVERSION_H */
